spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dion_v2?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: Dion
    password: Dion1234!

  jpa:
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: update

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 8082
  error:
    whitelabel:
      enabled: false

jwt:
  secret-key: "asflkjklqwoiasjdlfknlkclkjlkh123lknasdlfjh3849uasjdkfn289uo198hdnsjkfbkwje"
  access-exp: 10000
  refresh-exp: 10000